require('jreiter.comments')
require('jreiter.debug')
require('jreiter.git')
require('jreiter.telescope')
require('jreiter.lsp')
require('jreiter.completion')
require('jreiter.snippets')
require('jreiter.treesitter')
