local dap = require('dap')

dap.configurations.javascript = {
  {
    name = 'launch process',
    type = 'node2',
    request = 'launch',
    program = '${file}',
    cwd = vim.fn.getcwd(),
    protocol = 'inspector',
    console = 'integratedTerminal',
    skipFiles = {'<node_internals>/**/*.js'},
  },
  {
    name = 'attach to process',
    type = 'node2',
    request = 'attach',
    cwd = vim.fn.getcwd(),
    protocol = 'inspector',
    console = 'integratedTerminal',
    skipFiles = {'<node_internals>/**/*.js'},
  },
  {
    name = 'attach to remote process',
    type = 'node2',
    request = 'attach',
    address = '127.0.0.1',
    port = '9229',
    localRoot = vim.fn.getcwd(),
    remoteRoot = '/froggy/src',
    sourceMaps = true,
    protocol = 'inspector',
    console = 'integratedTerminal',
    skipFiles = {'<node_internals>/**/*.js'},
  },
  {
    name = 'sst start',
    type = 'node2',
    request = 'launch',
    program = '${workspaceFolder}/node_modules/.bin/sst',
    args = { 'start', '--increase-timeout'},
    cwd = vim.fn.getcwd(),
    protocol = 'inspector',
    console = 'integratedTerminal',
    skipFiles = {'<node_internals>/**/*.js'},
  },
  {
    name = 'sst tests',
    type = 'node2',
    request = 'launch',
    runtimeExecutable = 'npm',
    runtimeArgs = {'run-script', 'test', '--', '--runInBand', '--no-cache', '--watchAll=false'},
    -- args = {'--runInBand', '--no-cache', '--watchAll=false'},
    -- runtimeExecutable = '${workspaceFolder}/node_modules/.bin/sst',
    -- args = {'test', '--runInBand', '--no-cache', '--watchAll=false'},
    -- args = {'test', '--'},
    cwd = vim.fn.getcwd(),
    -- protocol = 'inspector',
    console = 'integratedTerminal',
    env = { CI = true },
    disableOptimisticBPs = true,
    outFiles = {'${workspaceFolder}/.build/*.js'},
    skipFiles = {'<node_internals>/**/*.js'},
  },
}
